### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 20481A05K0**
Hello Harsha!!
I have just simply updated the readme file which explains clearly regarding the execution of project

### CODE REVIEW

**Comment by 20481A05K0** [comment]
I have create a PR for you did you get it

**Review by HRS8 — APPROVED** [review]
ok lets see

**Comment by HRS8** [comment]
loose the list of dependencies and add a preview screenshot of the website! I have already merged PR but if don't create a new one with these changes I'll revert it

**Comment by 20481A05K0** [comment]
Ok sure Harsha I will add the screenshot but I didn't understand about loose the list of dependencies??

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 20481A05K0** [comment]
Got it 15 min I will do the changes

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
